# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'DefaultSuite' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
end
