# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'DefaultSuite' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'default' do
    @driver.get('http://127.0.0.1:3000/')
    #@driver.manage.resize_to(550, 692)
    @driver.find_element(:id, 'search_range').click
    @driver.find_element(:id, 'search_range').send_keys('7 1 4 9 14 16')
    @driver.find_element(:name, 'commit').click
    sleep 3
    @driver.find_element(:css, 'tr:nth-child(3) > td:nth-child(1)').click
    expect(@driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(1)').text).to eq('1,4,9')
    expect(@driver.find_element(:css, 'tr:nth-child(3) > td:nth-child(1)').text).to eq('16')
    expect(@driver.find_element(:css, 'tr:nth-child(5) > td:nth-child(1)').text).to eq('1,4,9')
    expect(@driver.find_element(:css, 'tr:nth-child(5) > td:nth-child(2)').text).to eq('3')
    sleep 3
  end
  it 'empty' do
    @driver.get('http://127.0.0.1:3000/')
    #@driver.manage.resize_to(550, 692)
    @driver.find_element(:id, 'search_range').click
    @driver.find_element(:name, 'commit').click
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:id, 'result') }
    sleep 3
    expect(@driver.find_element(:id, 'result').text).to eq('(myScript) Result is: no such sequences to output')
    sleep 3
  end
end
