# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'TestSuite0' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'xmlonlyformat' do
    @driver.get('http://127.0.0.1:3001/')
    @driver.find_element(:id, 'search_range').click
    @driver.find_element(:id, 'search_range').send_keys('7 1 4 9 14 16')
    @driver.find_element(:css, '.form-check:nth-child(3) > label').click
    @driver.find_element(:name, 'commit').click
    sleep 1
    elements = @driver.find_elements(:css, 'subsequence')
    expect(elements.length).to be > 0
    elements = @driver.find_elements(:css, 'length')
    expect(elements.length).to be > 0
    elements = @driver.find_elements(:css, 'object')
    expect(elements.length).to be > 0
  end
  it 'xmlclientvals' do
    @driver.get('http://127.0.0.1:3001/')
    @driver.find_element(:css, '.form-check:nth-child(3) > label').click
    @driver.find_element(:id, 'search_range').click
    @driver.find_element(:id, 'search_range').send_keys('3 3 4 3 16 25 5 36 64 1')
    @driver.find_element(:name, 'commit').click
    sleep 1
    expect(@driver.find_element(:css, '#folder1 .line:nth-child(2) > span:nth-child(2)').text).to eq('[4]')
    expect(@driver.find_element(:css, '#folder3 .line:nth-child(2) > span:nth-child(2)').text).to eq('[36, 64, 1]')
    expect(@driver.find_element(:css, '#folder5 .line:nth-child(2) > span:nth-child(2)').text).to eq('[36, 64, 1]')
  end
  it 'xmlclientincorrect' do
    @driver.get('http://127.0.0.1:3001/')
    @driver.find_element(:css, '.form-check:nth-child(3) > label').click
    @driver.find_element(:id, 'search_range').click
    @driver.find_element(:id, 'search_range').send_keys('jlbgkjkgb')
    @driver.find_element(:name, 'commit').click
    sleep 1
    expect(@driver.find_element(:css, '.line:nth-child(2) > span:nth-child(2)').text).to eq('error 2 - incorrect input')
  end
  it 'xmlclienterrorempty' do
    @driver.get('http://127.0.0.1:3001/')
    @driver.find_element(:css, '.form-check:nth-child(3) > label').click
    @driver.find_element(:name, 'commit').click
    sleep 1 
    expect(@driver.find_element(:css, '.line:nth-child(2) > span:nth-child(2)').text).to eq('error/code 3 - no sequences have been found')
  end
  it 'htmlservervals2' do
    @driver.get('http://127.0.0.1:3001/')
    @driver.find_element(:id, 'search_range').click
    @driver.find_element(:css, 'form').click
    @driver.find_element(:id, 'search_range').send_keys('3 5 9 1 25 3 4 16 3')
    @driver.find_element(:name, 'commit').click
    sleep 1
    expect(@driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(1)').text).to eq('[9, 1, 25]')
    expect(@driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(2)').text).to eq('3')
    expect(@driver.find_element(:css, 'tr:nth-child(3) > td:nth-child(1)').text).to eq('[4, 16]')
  end
  it 'htmlservervals1' do
    @driver.get('http://127.0.0.1:3001/')
    @driver.find_element(:id, 'search_range').click
    @driver.find_element(:id, 'search_range').send_keys('4 9 5 16 7')
    @driver.find_element(:name, 'commit').click
    sleep 1
    expect(@driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(1)').text).to eq('[4, 9]')
    expect(@driver.find_element(:css, 'tr:nth-child(3) > td:nth-child(1)').text).to eq('[16]')
    expect(@driver.find_element(:css, 'tr:nth-child(5) > td:nth-child(1)').text).to eq('[4, 9]')
    expect(@driver.find_element(:css, 'tr:nth-child(5) > td:nth-child(2)').text).to eq('2')
  end
  it 'htmlserverincorrect' do
    @driver.get('http://127.0.0.1:3001/')
    @driver.find_element(:id, 'search_range').click
    @driver.find_element(:id, 'search_range').send_keys('jvhv')
    @driver.find_element(:name, 'commit').click
    sleep 1
    expect(@driver.find_element(:xpath, '//p[2]').text).to eq('error 2 - incorrect input')
  end
  it 'htmlserverformat' do
    @driver.get('http://127.0.0.1:3001/')
    @driver.find_element(:id, 'search_range').click
    @driver.find_element(:id, 'search_range').send_keys('7 1 4 9 14 16')
    @driver.find_element(:name, 'commit').click
    sleep 1
    elements = @driver.find_elements(:css, 'table')
    expect(elements.length).to be > 0
    elements = @driver.find_elements(:css, 'td')
    expect(elements.length).to be > 0
  end
  it 'htmlclientformat' do
    @driver.get('http://127.0.0.1:3001/')
    @driver.find_element(:id, 'search_range').click
    @driver.find_element(:id, 'search_range').send_keys('7 1 4 9 14 16')
    @driver.find_element(:css, '.form-check:nth-child(4) > label').click
    @driver.find_element(:name, 'commit').click
    sleep 1
    elements = @driver.find_elements(:css, 'table')
    expect(elements.length).to be > 0
    elements = @driver.find_elements(:css, 'td')
    expect(elements.length).to be > 0
  end
  it 'htmlclienterrorempty' do
    @driver.get('http://127.0.0.1:3001/')
    @driver.find_element(:css, '.form-check:nth-child(4) > label').click
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, 'html').click
    sleep 1
    expect(@driver.find_element(:css, 'p').text).to eq('error/code 3 - no sequences have been found')
  end
end
